import dialectlibrary

dialect = dialectlibrary.DICTIONARY.copy()
dialect["and"] = "and"
dialect["as"] = "But call it"
dialect["assert"] = "Make sure that"
dialect["break"] = "Move on from this loop"
dialect["class"] = "What is a"
dialect["continue"] = "Handle the next iteration"
dialect["def"] = "How does it"
dialect["del"] = "Decrement the reference counter of"
dialect["elif"] = "If not and"
dialect["else"] = "If not then"
dialect["except"] = "So prepare for the exception(s)"
dialect["exec"] = "Execute"
dialect["finally"] = "Ensure this happens"
dialect["for"] = "For each"
dialect["from"] = "From the idea"
dialect["global"] = "Using the global value for"
dialect["if"] = "Supposing that"
dialect["import"] = "Import the idea of"
dialect["is"] = "Literally is"
dialect["lambda"] = "Short instruction"
dialect["not"] = "not"
dialect["or"] = "or"
dialect["pass"] = "Don't worry about it"
dialect["print"] = "Print to console"
dialect["raise"] = "Stop because there might be a problem"
dialect["return"] = "The result is"
dialect["try"] = "This might not work"
dialect["while"] = "While"
dialect["with"] = "In a new context, with"
dialect["yield"] = "Remember this context for later, lets work on"
#dialect["#"] = "Sidenote:" # does not work
dialect["="] = "="
dialect["!="] = "does not equal"
dialect[":"] = ":"
dialect[">="] = "is greater then or equal to"
dialect[">="] = "is less then or equal to"
dialect["=="] = "is equal to"

verbose_dialect = dialectlibrary.Dialect(**dialect)
