site_name: mpre
pages:
- ['index.md', 'Homepage']
- ['base_tutorial.md', 'Tutorial', 'Base objects']
- ['getting_started.md', 'Tutorial', 'Getting Started']
- ['Metaclass_features.md', 'Tutorial', 'Metaclass features']
- ['mpre\mpre.md', 'mpre', 'mpre']
- ['mpre\authentication.md', 'mpre', 'authentication']
- ['mpre\base.md', 'mpre', 'base']
- ['mpre\browser.md', 'mpre', 'browser']
- ['mpre\database.md', 'mpre', 'database']
- ['mpre\errors.md', 'mpre', 'errors']
- ['mpre\exe.md', 'mpre', 'exe']
- ['mpre\fileio.md', 'mpre', 'fileio']
- ['mpre\hkdf.md', 'mpre', 'hkdf']
- ['mpre\importers.md', 'mpre', 'importers']
- ['mpre\Life.md', 'mpre', 'Life']
- ['mpre\make_setup.md', 'mpre', 'make_setup']
- ['mpre\metaclass.md', 'mpre', 'metaclass']
- ['mpre\metapython.md', 'mpre', 'metapython']
- ['mpre\module_utilities.md', 'mpre', 'module_utilities']
- ['mpre\network.md', 'mpre', 'network']
- ['mpre\networkssl.md', 'mpre', 'networkssl']
- ['mpre\networkutilities.md', 'mpre', 'networkutilities']
- ['mpre\package.md', 'mpre', 'package']
- ['mpre\persistence.md', 'mpre', 'persistence']
- ['mpre\ptest.md', 'mpre', 'ptest']
- ['mpre\rpc.md', 'mpre', 'rpc']
- ['mpre\shell.md', 'mpre', 'shell']
- ['mpre\shell_launcher.md', 'mpre', 'shell_launcher']
- ['mpre\srp.md', 'mpre', 'srp']
- ['mpre\utilities.md', 'mpre', 'utilities']
- ['mpre\vmlibrary.md', 'mpre', 'vmlibrary']
- ['mpre\voip.md', 'mpre', 'voip']
- ['mpre\_compile.md', 'mpre', '_compile']
- ['mpre\_metapython.md', 'mpre', '_metapython']
- ['audio\audiolibrary.md', 'audio', 'audiolibrary']
- ['audio\audio_config_utility.md', 'audio', 'audio_config_utility']
- ['audio\capture_live_audio.md', 'audio', 'capture_live_audio']
- ['audio\play_wav_file.md', 'audio', 'play_wav_file']
- ['audio\portaudiodevices.md', 'audio', 'portaudiodevices']
- ['audio\wav_file_info.md', 'audio', 'wav_file_info']
- ['audio\utilities.md', 'audio', 'utilities']
- ['gui\gui.md', 'gui', 'gui']
- ['gui\sdllibrary.md', 'gui', 'sdllibrary']
- ['gui\shapes.md', 'gui', 'shapes']
- ['gui\widgetlibrary.md', 'gui', 'widgetlibrary']
- ['programs\create_documentation.md', 'programs', 'create_documentation']
- ['programs\create_self_signed_certificate.md', 'programs', 'create_self_signed_certificate']
- ['programs\register.md', 'programs', 'register']
- ['programs\stupidreceive.md', 'programs', 'stupidreceive']
- ['programs\stupidsend.md', 'programs', 'stupidsend']
- ['programs\unzip.md', 'programs', 'unzip']- ['mpre\__main__.md', 'mpre', '__main__']
- ['programs\unzip.md', 'programs', 'unzip']
- ['mpre\jsontest.md', 'mpre', 'jsontest']
- ['mpre\parser.md', 'mpre', 'parser']
