site_name: mpre
pages:
- ['index.md', 'Homepage']
- ['base_tutorial.md', 'Tutorial', 'Introduction']
- ['Building_a_Base_object.md', 'Tutorial', 'Building a Base object']
- ['Metaclass_features.md', 'Tutorial', 'Metaclass Features']
- ['mpre\base.md', 'mpre', 'base']
- ['mpre\buildproject.md', 'mpre', 'buildproject']
- ['mpre\defaults.md', 'mpre', 'defaults']
- ['mpre\keyboard.md', 'mpre', 'keyboard']
- ['mpre\metapython.md', 'mpre', 'metapython']
- ['mpre\networklibrary.md', 'mpre', 'networklibrary']
- ['mpre\networklibrary2.md', 'mpre', 'networklibrary2']
- ['mpre\package.md', 'mpre', 'package']
- ['mpre\shell_launcher.md', 'mpre', 'shell_launcher']
- ['mpre\stdin.md', 'mpre', 'stdin']
- ['mpre\utilities.md', 'mpre', 'utilities']
- ['mpre\vmlibrary.md', 'mpre', 'vmlibrary']
- ['audio\audiolibrary.md', 'audio', 'audiolibrary']
- ['audio\audio_config_utility.md', 'audio', 'audio_config_utility']
- ['audio\capture_live_audio.md', 'audio', 'capture_live_audio']
- ['audio\defaults.md', 'audio', 'defaults']
- ['audio\play_wav_file.md', 'audio', 'play_wav_file']
- ['audio\portaudiodevices.md', 'audio', 'portaudiodevices']
- ['audio\voipmessenger.md', 'audio', 'voipmessenger']
- ['gui\defaults.md', 'gui', 'defaults']
- ['gui\guilibrary.md', 'gui', 'guilibrary']
- ['gui\sdllibrary.md', 'gui', 'sdllibrary']
- ['gui\sdltest.md', 'gui', 'sdltest']
- ['gui\widgetlibrary.md', 'gui', 'widgetlibrary']
- ['misc\convert_bases.md', 'misc', 'convert_bases']
- ['misc\decoratorlibrary.md', 'misc', 'decoratorlibrary']
- ['misc\decoratorlibrary2.md', 'misc', 'decoratorlibrary2']
- ['misc\dialectlibrary.md', 'misc', 'dialectlibrary']
- ['misc\downloadtest.md', 'misc', 'downloadtest']
- ['misc\mmaptest.md', 'misc', 'mmaptest']
- ['misc\securitylibrary.md', 'misc', 'securitylibrary']
- ['misc\verbosedialect.md', 'misc', 'verbosedialect']
- ['programs\bytecodedis.md', 'programs', 'bytecodedis']
- ['programs\bytecodemap.md', 'programs', 'bytecodemap']
- ['programs\compile.md', 'programs', 'compile']
- ['programs\create_package.md', 'programs', 'create_package']
- ['programs\download_file.md', 'programs', 'download_file']
- ['programs\file_server.md', 'programs', 'file_server']
- ['programs\get_modules.md', 'programs', 'get_modules']
- ['programs\remote_connection.md', 'programs', 'remote_connection']
- ['programs\send_file.md', 'programs', 'send_file']
- ['programs\stupidreceive.md', 'programs', 'stupidreceive']
- ['programs\stupidsend.md', 'programs', 'stupidsend']
