site_name: mpre
pages:
- ['index.md', 'Homepage']
- ['base_tutorial.md', 'Tutorial', 'Base objects']
- ['Building_a_Base_object.md', 'Tutorial', 'Base objects 2']
- ['Metaclass_features.md', 'Tutorial', 'Metaclass features']
- ['mpre\base.md', 'mpre', 'base']
- ['mpre\defaults.md', 'mpre', 'defaults']
- ['mpre\fileio.md', 'mpre', 'fileio']
- ['mpre\metaclass.md', 'mpre', 'metaclass']
- ['mpre\metapython.md', 'mpre', 'metapython']
- ['mpre\network.md', 'mpre', 'network']
- ['mpre\network2.md', 'mpre', 'network2']
- ['mpre\package.md', 'mpre', 'package']
- ['mpre\shell_launcher.md', 'mpre', 'shell_launcher']
- ['mpre\userinput.md', 'mpre', 'userinput']
- ['mpre\utilities.md', 'mpre', 'utilities']
- ['mpre\vmlibrary.md', 'mpre', 'vmlibrary']
- ['audio\audiolibrary.md', 'audio', 'audiolibrary']
- ['audio\audio_config_utility.md', 'audio', 'audio_config_utility']
- ['audio\capture_live_audio.md', 'audio', 'capture_live_audio']
- ['audio\defaults.md', 'audio', 'defaults']
- ['audio\play_wav_file.md', 'audio', 'play_wav_file']
- ['audio\portaudiodevices.md', 'audio', 'portaudiodevices']
- ['audio\utilities.md', 'audio', 'utilities']
- ['gui\defaults.md', 'gui', 'defaults']
- ['gui\guilibrary.md', 'gui', 'guilibrary']
- ['gui\sdllibrary.md', 'gui', 'sdllibrary']
- ['gui\widgetlibrary.md', 'gui', 'widgetlibrary']
- ['misc\attributetest.md', 'misc', 'attributetest']
- ['misc\bytecodedis.md', 'misc', 'bytecodedis']
- ['misc\bytecodemap.md', 'misc', 'bytecodemap']
- ['misc\compile.md', 'misc', 'compile']
- ['misc\compresstest.md', 'misc', 'compresstest']
- ['misc\convert_bases.md', 'misc', 'convert_bases']
- ['misc\decoratorlibrary.md', 'misc', 'decoratorlibrary']
- ['misc\decoratorlibrary2.md', 'misc', 'decoratorlibrary2']
- ['misc\dialectlibrary.md', 'misc', 'dialectlibrary']
- ['misc\scratch.md', 'misc', 'scratch']
- ['misc\securitylibrary.md', 'misc', 'securitylibrary']
- ['misc\verbosedialect.md', 'misc', 'verbosedialect']
- ['programs\build_metapython_package.md', 'programs', 'build_metapython_package']
- ['programs\download_file.md', 'programs', 'download_file']
- ['programs\file_server.md', 'programs', 'file_server']
- ['programs\get_modules.md', 'programs', 'get_modules']
- ['programs\remote_connection.md', 'programs', 'remote_connection']
- ['programs\send_file.md', 'programs', 'send_file']
- ['programs\stupidreceive.md', 'programs', 'stupidreceive']
- ['programs\stupidsend.md', 'programs', 'stupidsend']
- ['tests\bytecodedis.md', 'tests', 'bytecodedis']
- ['tests\bytecodemap.md', 'tests', 'bytecodemap']
- ['tests\hashdicttest.md', 'tests', 'hashdicttest']
- ['tests\installtest.md', 'tests', 'installtest']
- ['tests\lru_test.md', 'tests', 'lru_test']
- ['tests\network2.md', 'tests', 'network2']
