site_name: pride
pages:
- ['index.md', 'Homepage']
- ['pride\additional_builtins.md', 'pride', 'additional_builtins']
- ['pride\additional_keywords.md', 'pride', 'additional_keywords']
- ['pride\asciitest.md', 'pride', 'asciitest']
- ['pride\asymmetrictest.md', 'pride', 'asymmetrictest']
- ['pride\authentication2.md', 'pride', 'authentication2']
- ['pride\base.md', 'pride', 'base']
- ['pride\blackbox.md', 'pride', 'blackbox']
- ['pride\browser.md', 'pride', 'browser']
- ['pride\contextmanagers.md', 'pride', 'contextmanagers']
- ['pride\cryptographyless.md', 'pride', 'cryptographyless']
- ['pride\database.md', 'pride', 'database']
- ['pride\datastructures.md', 'pride', 'datastructures']
- ['pride\datatransfer.md', 'pride', 'datatransfer']
- ['pride\decorators.md', 'pride', 'decorators']
- ['pride\dtstest.md', 'pride', 'dtstest']
- ['pride\errors.md', 'pride', 'errors']
- ['pride\executable2.md', 'pride', 'executable2']
- ['pride\fileio.md', 'pride', 'fileio']
- ['pride\hkdf.md', 'pride', 'hkdf']
- ['pride\importers.md', 'pride', 'importers']
- ['pride\__main__.md', 'pride', '__main__']
- ['pride\loadtest.md', 'pride', 'loadtest']
- ['pride\main.md', 'pride', 'main']
- ['pride\make_setup.md', 'pride', 'make_setup']
- ['pride\malbolge.md', 'pride', 'malbolge']
- ['pride\metaclass.md', 'pride', 'metaclass']
- ['pride\module_utilities.md', 'pride', 'module_utilities']
- ['pride\network.md', 'pride', 'network']
- ['pride\networkssl.md', 'pride', 'networkssl']
- ['pride\networkutilities.md', 'pride', 'networkutilities']
- ['pride\objectfinder.md', 'pride', 'objectfinder']
- ['pride\package.md', 'pride', 'package']
- ['pride\patch.md', 'pride', 'patch']
- ['pride\persistence.md', 'pride', 'persistence']
- ['pride\preprocessing.md', 'pride', 'preprocessing']
- ['pride\recordservice.md', 'pride', 'recordservice']
- ['pride\rpc.md', 'pride', 'rpc']
- ['pride\securedatatransfer.md', 'pride', 'securedatatransfer']
- ['pride\security.md', 'pride', 'security']
- ['pride\shell.md', 'pride', 'shell']
- ['pride\shell_launcher.md', 'pride', 'shell_launcher']
- ['pride\site_config.md', 'pride', 'site_config']
- ['pride\timingcomparison.md', 'pride', 'timingcomparison']
- ['pride\user.md', 'pride', 'user']
- ['pride\utilities.md', 'pride', 'utilities']
- ['pride\vcs.md', 'pride', 'vcs']
- ['pride\vmlibrary.md', 'pride', 'vmlibrary']
- ['pride\_compile.md', 'pride', '_compile']
- ['pride\_termsize.md', 'pride', '_termsize']
- ['audio\audiolibrary.md', 'audio', 'audiolibrary']
- ['audio\audio_config_utility.md', 'audio', 'audio_config_utility']
- ['audio\capture_live_audio.md', 'audio', 'capture_live_audio']
- ['audio\play_wav_file.md', 'audio', 'play_wav_file']
- ['audio\portaudiodevices.md', 'audio', 'portaudiodevices']
- ['crypto\aestest.md', 'crypto', 'aestest']
- ['crypto\aes_procedures.md', 'crypto', 'aes_procedures']
- ['crypto\augpake.md', 'crypto', 'augpake']
- ['crypto\bitpermutation.md', 'crypto', 'bitpermutation']
- ['crypto\bitpermutationtest.md', 'crypto', 'bitpermutationtest']
- ['crypto\blockcipher.md', 'crypto', 'blockcipher']
- ['crypto\blockcipher2.md', 'crypto', 'blockcipher2']
- ['crypto\blockcipher3.md', 'crypto', 'blockcipher3']
- ['crypto\branchcount.md', 'crypto', 'branchcount']
- ['crypto\collisionreference.md', 'crypto', 'collisionreference']
- ['crypto\collisiontesting.md', 'crypto', 'collisiontesting']
- ['crypto\collisiontesting2.md', 'crypto', 'collisiontesting2']
- ['crypto\convert2test.md', 'crypto', 'convert2test']
- ['crypto\cryptochallengeprogress.md', 'crypto', 'cryptochallengeprogress']
- ['crypto\cryptosecipher.md', 'crypto', 'cryptosecipher']
- ['crypto\crypttest.md', 'crypto', 'crypttest']
- ['crypto\cyclelengthtest.md', 'crypto', 'cyclelengthtest']
- ['crypto\deadbeeftest.md', 'crypto', 'deadbeeftest']
- ['crypto\decorrelationtest.md', 'crypto', 'decorrelationtest']
- ['crypto\decorrelationtest2.md', 'crypto', 'decorrelationtest2']
- ['crypto\diffusiontechniques.md', 'crypto', 'diffusiontechniques']
